### ISSUE TITLE
调试页面没有出现

### ISSUE THREAD

**Issue by zengguangzhong** [liriliri/whistle.chii#3]
![image](https://user-images.githubusercontent.com/20290798/102857054-b63f0800-4462-11eb-80d4-3be4811b1f86.png)
配置了以上两个规则，打开插件，如下图：

![image](https://user-images.githubusercontent.com/20290798/102856991-9a3b6680-4462-11eb-8ca1-91da220e12b3.png)

没有出现手机上打开的页面呢？

**Comment by mlxiao93** [comment]
同样的情况，demo页报错，devtools出不来
![image](https://user-images.githubusercontent.com/17188706/131882530-abd459a3-e8d6-4ff0-be0e-6677b7e1de0e.png)

**Comment by hrjoyce1990** [comment]
sudo whistle start -p 80   ,这样尝试后可以。 ps：ios15后NSURLSession开启的无法创建ws，safri可以设置关闭，但APP内的WKWebView还在找解决方案中。

**Comment by soakit** [comment]
> 

  app内的有解决方案了吗？

**Comment by surunzi** [comment]
看起来不像这边的问题
