### ISSUE TITLE
Other Error

### ISSUE THREAD

**Issue by Panfen** [liriliri/whistle.chii#4]
Pages下点击inspect查看页面，提示：
Other Error
[D]Other Error|dial tcp4 127.0.0.1:80: connect: connection refused

Windows 10，
Nodejs: 10.23.0
chii: 0.1.0
whistle: 2.6.7
80端口和whistle的8899端口均已加入防火墙白名单

**Comment by surunzi** [comment]
无法复现，看起来不像是这边的问题。
